### ISSUE TITLE
Option to disable or change value of "slow internet".

### ISSUE THREAD

**Issue by sohate** [FuzzyIdeas/IsThereNet#1]
Hello! Thanks for app. Any chance for option for disabling "slow internet" or change it's value?

**Comment by sohate** [comment]
It would be great if you also add an option for deleting green bar too.

**Comment by alin23** [comment]
Hi! Sorry, for now I'd like to keep the app as simple as possible. No UI, no options etc. I don't have time to develop it further at the moment. 

You can change the value and compile it yourself if you'd prefer.

**Comment by alin23** [comment]
[v1.2](https://github.com/FuzzyIdeas/IsThereNet/releases/tag/v1.2) adds hysteresis logic which should lower the chances of seeing continuous changes between `YELLOW` and `GREEN` states.
