### ISSUE TITLE
Editing The Config File / Respecting Focus.

### ISSUE THREAD

**Issue by Spoekenkieker** [FuzzyIdeas/IsThereNet#10]
Hello @alin23,

first, please forgive me if I am doing something wrong with this issue (like, this being about TWO things: sound and Focus) — I have mostly only been _reading_ about my favourite apps (etc.) on Github, and I don't know about “correct” communication here.

I’m a huge fan of your great little app, as I live out in the country with a sometimes flaky internet connection … and I was very glad to read that you added **sound** in v1.5:
> This can now be adjusted in [v1.5](https://github.com/FuzzyIdeas/IsThereNet/releases/tag/v1.5)
> […]

The pathname of the config file is `~/Library/Containers/com.lowtechguys.IsThereNet/Data/Library/Preferences/com.lowtechguys.IsThereNet.plist`, correct?

Despite me using v1.5 this file hasn’t been touched since 2024-06-08 😮 And it looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSStatusItem Visible Item-0</key>
	<false/>
	IsThereNet
</dict>
</plist>
```

But can you please tell this dummy user  _where_ in the config file to add the following snippet?
```
"sounds" : {
    "volume" : 0.7,
    "connected" : "",
    "disconnected" : "",
    "slow" : ""
  }
```
I’m NOT a coder but I _do_ know how to edit a file with BBedit if someone tells me what to copy/paste where, I also understand that I’ll have to insert the sound file names between those double quotation marks in the 3rd, 4th, and 5th line 😅
BUT, full pathname or does the name of the file suffice?
________________

On said page you also write:
> The app will detect Do Not Disturb and other Focus states

As I often sit at the computer late at night, far into my “sleep” focus 🙄 I find it good that most notifications are hidden from me but THIS notification I’d still want to see … would it be possible to make this optional?

TIA,
Tom in Germany

**Comment by alin23** [comment]
Aș you can read in the [v1.4](https://github.com/FuzzyIdeas/IsThereNet/releases/tag/v1.4) release:

> The config can be found at: `~/Library/Containers/com.lowtechguys.IsThereNet/Data/Library/Application Support/config.json`

So you got that config path wrong, not sure where you got it from, but no worries 😌 We're using a config.json file for this. The plist file is for preferences that can be changed from the app UI (which we don't have)

If the config does not already have those lines for sound, delete the config file and restart the app and you should get a fresh config file again.

**Comment by Spoekenkieker** [comment]
Awesome, works, thank you! 🙏🙇‍♂️
