### ISSUE TITLE
Bar doesn't fill top edge on non-notch screens

### ISSUE THREAD

**Issue by tech189** [FuzzyIdeas/IsThereNet#11]
<img width="1440" alt="Screenshot 2024-07-17 at 23 11 56" src="https://github.com/user-attachments/assets/2f4eea1c-5cc1-4b76-8949-de9fabdeb38b">
Thanks for this app it's really useful! As you can see in the screenshot above, the bar doesn't quite fill the whole of the top edge of the display on my non-notch MacBook, it's just a few pixels off on the right hand side. Would love to have this fill my menu bar completely!

**Comment by alin23** [comment]
Should be fixed in [v1.6](https://github.com/FuzzyIdeas/IsThereNet/releases/tag/v1.6)
