### ISSUE TITLE
1.6 “no longer sandboxed” — Use other sounds than macOS system sounds?

### ISSUE THREAD

**Issue by Spoekenkieker** [FuzzyIdeas/IsThereNet#12]
Hello,

in the notes for 1.6 you write, “no longer sandboxed” … does this mean we can now use our own sounds?

If YES, how would that work?
Currently I just insert the filename (without extension) … now, IF we can user own sounds, I assume we’d need to insert pathname?
And what have I forgotten to ask? 😅

THANKS so much for this awesome and very helpful little app!

Cordially,
Tom in rural North Germany with flaky net

**Comment by alin23** [comment]
I'll need to make a small change to allow arbitrary file paths, but great idea, thanks for letting me know about it 😊

**Comment by alin23** [comment]
This was just added in [v1.6.1](https://github.com/FuzzyIdeas/IsThereNet/releases/tag/v1.6.1)

**Comment by Spoekenkieker** [comment]
BTW, after launching ITN 1.6.1, it shows me this:
![image](https://github.com/user-attachments/assets/44b92ae0-2f64-4813-bd59-1aecaf4000d4)
I can close it, and ITN runs fine, but I wonder (ofc) …

**Comment by alin23** [comment]
> BTW, after launching ITN 1.6.1, it shows me this:
> 
> ![image](https://github.com/user-attachments/assets/44b92ae0-2f64-4813-bd59-1aecaf4000d4)
> 
> I can close it, and ITN runs fine, but I wonder (ofc) …

🤔 is this on the macOS Sequoia beta?

**Comment by Spoekenkieker** [comment]
Oh DANG, yes, macOS 15 Sequoia Public beta, SORRY for forgetting to mention … when I read the release notes in the email already I realised that I had done THE UNFORGIVABLE, namely not mentioning it 😬 😅 I’m getting old (aged 67) … thanks for being so kind as not to condescend!
