### ISSUE TITLE
default download ARM-only, unusable on intel

### ISSUE THREAD

**Issue by core-code** [FuzzyIdeas/IsThereNet#13]
https://files.lowtechguys.com/releases/IsThereNet.dmg
=>
<img width="267" alt="Screenshot 2024-08-14 at 15 36 29" src="https://github.com/user-attachments/assets/7295600b-bf19-4073-a5a1-f827c1416bf2">

**Comment by alin23** [comment]
Indeed, not sure what went wrong with the last build. I'm uploading a fixed one in a few minutes

**Comment by alin23** [comment]
Should be fixed now.

**Comment by core-code** [comment]
thanks for the quick fix
