### ISSUE TITLE
Empty window on Sequoia

### ISSUE THREAD

**Issue by pmcarrion** [FuzzyIdeas/IsThereNet#14]
After upgrading to macOS Sequoia 15.0 (24A335), IsThereNet now shows an empty window when logging in.

**Comment by alin23** [comment]
Try updating to the latest version which fixed this: https://github.com/FuzzyIdeas/IsThereNet/releases/

**Comment by gy-mate** [comment]
@alin23 I'm using `1.6.2` (thanks to the auto-updater) but I still see this window at login: 
<img width="1012" alt="Screenshot 2024-10-05 at 15 39 45" src="https://github.com/user-attachments/assets/7fc2deac-0be3-48f5-a1e8-8569307e970b">

I actually added the app to _Open at Login_ earlier so I don't have to open it every time I restart my Mac:
<img width="477" alt="Screenshot 2024-10-05 at 15 41 06" src="https://github.com/user-attachments/assets/79251e76-4419-4233-b43b-9d5695977356">
Is this a problem?

**Comment by alin23** [comment]
> @alin23 I'm using the latest version (`1.6.2`—thanks to the auto-updater) but I still see this window at login: 
> 
> <img width="1012" alt="Screenshot 2024-10-05 at 15 39 45" src="https://github.com/user-attachments/assets/7fc2deac-0be3-48f5-a1e8-8569307e970b">
> 
> 
> 
> I actually added the app to _Open at Login_ earlier so I don't have to launch it manually every time I restart my Mac:
> 
> <img width="477" alt="Screenshot 2024-10-05 at 15 41 06" src="https://github.com/user-attachments/assets/79251e76-4419-4233-b43b-9d5695977356">
> 
> Is this a problem?
> 
> 
> 
> _I'm using macOS `15.0.1`._

Try downloading again from the website or from Releases, there was a bug in the release logic and 1.6.2 got released without the change at first.

**Comment by gy-mate** [comment]
I see, thanks, will do!
