### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 3x071c** [FuzzyIdeas/IsThereNet#4]
Hey, is this app licensed under the `GPLv3` like some of your other projects or are there special terms to consider? Currently, it looks like there's no license conditions, (perhaps inadvertently) [making the source code non-free](https://choosealicense.com/no-permission/). This would also make it possible to package as a homebrew formula :)

**Comment by alin23** [comment]
Yes, sorry, it's GPLv3. I just added the license file.
