### ISSUE TITLE
please register to brew cask registry

### ISSUE THREAD

**Issue by ryoppippi** [FuzzyIdeas/IsThereNet#5]
HI!
I really like this app!

I'd like to download it from brew cask

**Comment by alin23** [comment]
[Not all apps are allowed there](https://docs.brew.sh/Acceptable-Casks#rejected-casks), IsThereNet needs to become a bit more popular for that:

![Firefox Developer Edition-005701-Friday-13-22](https://github.com/FuzzyIdeas/IsThereNet/assets/3819725/020ee0c7-3300-4eea-ab50-2e3b2d2bc7c9)
