### ISSUE TITLE
Proposal to Make IP Address Configurable

### ISSUE THREAD

**Issue by Farhaduneci** [FuzzyIdeas/IsThereNet#7]
Hi there,
First, I want to thank you for your great app! 💫

I have noticed that the IP address `1.1.1.1` is hardcoded in the project. While I understand and appreciate the rationale behind this choice, the hardcoded IP address presents significant challenges for me here in Iran hence that's blocked or noisy most of the time. 🫠

Currently, changing the IP address necessitates direct modifications to the source code. To enhance flexibility, I propose making the IP address configurable through an environment variable. This can easily be achieved with a small code change like the following:

```swift
let ipAddress = ProcessInfo.processInfo.environment["ISTHERENET_TARGET_IP"] ?? "1.1.1.1"
```

I believe this adjustment will be beneficial for users who encounter similar issues or have different requirements. I am more than willing to contribute this feature to the project if you find the change acceptable.

Please share your thoughts on this suggestion.
Thank you!

**Comment by alin23** [comment]
Hi Farhad! Makes sense what you're proposing. I think I'll go ahead and add support for a config file like `~/.istherenet` or something. That way I can integrate more configuration that was asked for (like timeouts, delay time etc.) as well as the IP address I'm pinging, without needing to add an UI

**Comment by Farhaduneci** [comment]
That's great. Let me know if you need help. ✌️

**Comment by alin23** [comment]
Done here: https://github.com/FuzzyIdeas/IsThereNet/releases/tag/v1.4

**Comment by Farhaduneci** [comment]
Thanks 👍

**Comment by Farhaduneci** [comment]
Thank you, @alin23! This addition is truly appreciated. ✨
Great job on the update, and thanks for considering my feedback!
