### ISSUE TITLE
update check or brew package

### ISSUE THREAD

**Issue by IoannisTM** [FuzzyIdeas/IsThereNet#9]
Hello,
I have been using this app for some time now but never realized that there was a new version released.
Any possibility to add either an update check or a brew package?

Very nice app btw.
Thanks

**Comment by alin23** [comment]
For brew, the app needs to be more popular: https://github.com/FuzzyIdeas/IsThereNet/issues/5

The update check can be done, I didn't expect to add anymore features to the app but I guess I will so auto updating is needed.

**Comment by alin23** [comment]
Auto updating was just added in [v1.6](https://github.com/FuzzyIdeas/IsThereNet/releases/tag/v1.6)

**Comment by danilokleber** [comment]
Is it possible to turn it off?

**Comment by alin23** [comment]
> Is it possible to turn it off?

Sure, the app should prompt you on a second launch if you want to enable or disable automatic update checks.

You can also disable them manually using the following terminal command:

```sh
defaults write com.lowtechguys.IsThereNet SUEnableAutomaticChecks false
```

**Comment by ShlomoCode** [comment]
@alin23 You can add your own tap
for example:
```bash
brew tap caskroom/fonts
brew install --cask fontforge
```
